#!/bin/bash

version: '3.6'

services:

  db:
    image: postgres:15.4
    container_name: prj-db-container_from_compose
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    env_file:
#      - ./.env
    volumes:
      - ./src/data/postgres-backup/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - prj-network_from_compose

  api:
    build:
      context: ./src/api/
      dockerfile: Dockerfile
    container_name: prj-fastapi-container_from_compose
    expose:
      - 8085
    ports:
      - '8085:8085'
    volumes:
      - ./requirements.txt:/code/requirements.txt
      - ./src:/code/src
      - ./models/model.pkl:/code/models/model.pkl
    #env_file:
    #  - ./.env
    environment:
      - secret=${secret}
      - algorithm=${algorithm}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      #- POSTGRES_URL=${POSTGRES_URL}
      #- RDS_URL=${RDS_URL}
    depends_on:
      - db
    restart: always
    networks:
      - prj-network_from_compose

volumes:
  postgres-db-volume:

networks:
  prj-network_from_compose:
    #driver: bridge  

